apiVersion: v1
kind: Service
metadata:
  name: sre-demo-service
  labels:
    app: sre-demo
spec:
  type: LoadBalancer
  selector:
    app: sre-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
